# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0005_auto_20180119_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='Test', max_length=100, unique=True, verbose_name='Slug (URL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Test', max_length=60, unique=True, verbose_name='Slug (URL)'),
            preserve_default=False,
        ),
    ]
