# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_auto_20180122_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pin_priority',
            field=models.IntegerField(default=0, verbose_name='Pinned post priority (if pinned)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pin blog post'),
        ),
    ]
