# Generated by Django 2.1.3 on 2019-01-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_auto_20180329_1316'),
        ('weblog', '0008_auto_20180531_0329'),
    ]

    operations = [
    ]
